server:
  host: "localhost"
  port: 8080


database:
  host: "localhost"
  port: 5433
  username: "postgres"
  password: "postgres"
  database: "sms"

rabbitmq:
  uri: "amqp://guest:guest@localhost:5672/"
  queues:
    # These queues are the queues that finance service should listen to
    #TODO: change me
    - name: "sms_sms.billing.requested"
      exchange: "amq.topic"
      routing_key: "sms.billing.requested"
 
