definitions:
  dto.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
  dto.SendSMSRequest:
    properties:
      content:
        maxLength: 160
        type: string
      receiver:
        description: E.164 format phone number
        type: string
      user_id:
        type: string
    required:
    - content
    - receiver
    - user_id
    type: object
  dto.SendSMSResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /sms:
    post:
      consumes:
      - application/json
      description: Send an SMS message to a specified receiver
      parameters:
      - description: SMS request payload
        in: body
        name: sms
        required: true
        schema:
          $ref: '#/definitions/dto.SendSMSRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SendSMSResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Send an SMS message
      tags:
      - SMS
swagger: "2.0"
